# Generated by Django 5.2.8 on 2025-11-29 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mintcastiq', '000X_seed_grades'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactInventoryDetail',
            fields=[
                ('status', models.CharField(choices=[('a', 'active'), ('i', 'inactive')], db_index=True, default='a', max_length=1)),
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('acquired_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('identity_string', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('upc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'fact_inventory_detail',
            },
        ),
        migrations.RemoveField(
            model_name='dimcardhash',
            name='card',
        ),
        migrations.RemoveField(
            model_name='dimcardparallel',
            name='parallel',
        ),
        migrations.RemoveField(
            model_name='dimcardparallel',
            name='set',
        ),
        migrations.RemoveField(
            model_name='factchecklistitem',
            name='card',
        ),
        migrations.RemoveField(
            model_name='factchecklistitem',
            name='parallel',
        ),
        migrations.RemoveField(
            model_name='factchecklistitem',
            name='set',
        ),
        migrations.RemoveField(
            model_name='factinventory',
            name='checklist_item',
        ),
        migrations.RemoveConstraint(
            model_name='factinventory',
            name='unique_inventory',
        ),
        migrations.RemoveField(
            model_name='dimcard',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='dimparallel',
            name='parallel_type',
        ),
        migrations.RemoveField(
            model_name='factinventory',
            name='acquired_at',
        ),
        migrations.RemoveField(
            model_name='factinventory',
            name='card',
        ),
        migrations.RemoveField(
            model_name='factinventory',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='factinventory',
            name='identity_string',
        ),
        migrations.RemoveField(
            model_name='factinventory',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='factinventory',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='factinventory',
            name='source',
        ),
        migrations.AddField(
            model_name='dimcard',
            name='stock_image_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dimcard',
            name='stock_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='factinventorydetail',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimcard'),
        ),
        migrations.AddField(
            model_name='factinventorydetail',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimgrade'),
        ),
        migrations.AddField(
            model_name='factinventorydetail',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.factinventory'),
        ),
        migrations.DeleteModel(
            name='DimCardHash',
        ),
        migrations.DeleteModel(
            name='DimCardParallel',
        ),
        migrations.DeleteModel(
            name='FactChecklistItem',
        ),
        migrations.AddConstraint(
            model_name='factinventorydetail',
            constraint=models.UniqueConstraint(fields=('identity_string',), name='unique_inventory_detail'),
        ),
    ]
