# Generated by Django 5.2.8 on 2025-11-26 06:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimCard',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('edition', models.TextField(blank=True, null=True)),
                ('format', models.TextField(blank=True, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_card',
            },
        ),
        migrations.CreateModel(
            name='DimGrade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grading_standard', models.TextField()),
                ('numeric_value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('grade_label', models.TextField()),
                ('overlay_ref', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_grade',
            },
        ),
        migrations.CreateModel(
            name='DimParallel',
            fields=[
                ('parallel_id', models.AutoField(primary_key=True, serialize=False)),
                ('parallel_name', models.TextField()),
                ('parallel_type', models.TextField(blank=True, null=True)),
                ('print_run', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_parallel',
            },
        ),
        migrations.CreateModel(
            name='DimSet',
            fields=[
                ('set_id', models.AutoField(primary_key=True, serialize=False)),
                ('set_name', models.TextField()),
                ('publisher', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('set_year', models.CharField(blank=True, max_length=10, null=True)),
                ('ssubset_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dim_set',
            },
        ),
        migrations.CreateModel(
            name='DimUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('otp_delivery', models.CharField(blank=True, max_length=10, null=True)),
                ('is_admin', models.BooleanField(blank=True, null=True)),
                ('is_contributor', models.BooleanField(blank=True, null=True)),
                ('invited', models.BooleanField(blank=True, null=True)),
                ('join_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('role', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_users',
            },
        ),
        migrations.CreateModel(
            name='DimCardHash',
            fields=[
                ('hash_id', models.AutoField(primary_key=True, serialize=False)),
                ('hash_value', models.TextField()),
                ('hash_type', models.TextField()),
                ('hash_position', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimcard')),
            ],
            options={
                'db_table': 'dim_card_hash',
            },
        ),
        migrations.AddField(
            model_name='dimcard',
            name='parallel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimparallel'),
        ),
        migrations.AddField(
            model_name='dimparallel',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimset'),
        ),
        migrations.AddField(
            model_name='dimcard',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimset'),
        ),
        migrations.CreateModel(
            name='DimSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimusers')),
            ],
            options={
                'db_table': 'dim_sessions',
            },
        ),
        migrations.CreateModel(
            name='FactCardEvents',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('action_type', models.TextField()),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimcard')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimgrade')),
                ('set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimset')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimusers')),
            ],
            options={
                'db_table': 'fact_card_events',
            },
        ),
        migrations.CreateModel(
            name='FactChecklistItem',
            fields=[
                ('checklist_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimcard')),
                ('parallel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimparallel')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimset')),
            ],
            options={
                'db_table': 'fact_checklist_item',
            },
        ),
        migrations.CreateModel(
            name='FactInventory',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('acquired_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('checklist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.factchecklistitem')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimgrade')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimusers')),
            ],
            options={
                'db_table': 'fact_inventory',
            },
        ),
        migrations.CreateModel(
            name='FactMetrics',
            fields=[
                ('metric_id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_name', models.TextField()),
                ('metric_value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('unit', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.factcardevents')),
            ],
            options={
                'db_table': 'fact_metrics',
            },
        ),
    ]
