# Generated by Django 5.2.8 on 2025-12-16 11:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='checklists/')),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'checklist_upload',
            },
        ),
        migrations.CreateModel(
            name='DimSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('identity_string', models.TextField(editable=False)),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('set_name', models.CharField(max_length=128)),
                ('publisher', models.CharField(max_length=64)),
                ('set_year', models.CharField(max_length=32)),
                ('subset_name', models.CharField(blank=True, max_length=128, null=True)),
                ('brand', models.CharField(blank=True, max_length=64, null=True)),
                ('sport', models.CharField(blank=True, max_length=32, null=True)),
                ('set_code', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DimUsers',
            fields=[
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('identity_string', models.TextField(editable=False)),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('otp_delivery', models.CharField(blank=True, max_length=10, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_contributor', models.BooleanField(default=False)),
                ('invited', models.BooleanField(default=False)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dim_users',
            },
        ),
        migrations.CreateModel(
            name='DimGrade',
            fields=[
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('identity_string', models.TextField(editable=False)),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grading_standard', models.CharField(db_index=True, default='RAW', max_length=50)),
                ('numeric_value', models.DecimalField(decimal_places=1, max_digits=10)),
                ('grade_label', models.CharField(max_length=255)),
                ('overlay_ref', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'dim_grade',
                'constraints': [models.UniqueConstraint(fields=('grading_standard', 'numeric_value', 'grade_label'), name='unique_grade')],
            },
        ),
        migrations.CreateModel(
            name='DimParallel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='ACTIVE', max_length=32)),
                ('identity_string', models.TextField(editable=False)),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('parallel_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dim_parallel',
                'constraints': [models.UniqueConstraint(fields=('parallel_id',), name='uq_parallel_id')],
            },
        ),
        migrations.CreateModel(
            name='DimCard',
            fields=[
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('identity_string', models.TextField(editable=False)),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('team_name', models.CharField(max_length=64)),
                ('card_number', models.CharField(max_length=25)),
                ('stock_image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cardset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mintcastiq.dimset')),
            ],
            options={
                'db_table': 'dim_card',
            },
        ),
        migrations.CreateModel(
            name='DimSessions',
            fields=[
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('identity_string', models.TextField(editable=False)),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mintcastiq.dimusers')),
            ],
            options={
                'db_table': 'dim_sessions',
            },
        ),
        migrations.CreateModel(
            name='FactCardEvents',
            fields=[
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('identity_string', models.TextField(editable=False)),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_type', models.CharField(max_length=255)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mintcastiq.dimcard')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mintcastiq.dimgrade')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mintcastiq.dimset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mintcastiq.dimusers')),
            ],
            options={
                'db_table': 'fact_card_events',
            },
        ),
        migrations.CreateModel(
            name='FactInventory',
            fields=[
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('identity_string', models.TextField(editable=False)),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mintcastiq.dimusers')),
            ],
            options={
                'db_table': 'fact_inventory',
            },
        ),
        migrations.CreateModel(
            name='FactPlayerMaster',
            fields=[
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('identity_string', models.TextField(editable=False)),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=128)),
                ('player_name', models.CharField(max_length=64)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mintcastiq.dimcard')),
                ('parallel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mintcastiq.dimparallel')),
            ],
            options={
                'db_table': 'fact_player_master',
            },
        ),
        migrations.CreateModel(
            name='FactTeamMaster',
            fields=[
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('identity_string', models.TextField(editable=False)),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=128)),
                ('team_name', models.CharField(max_length=64)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mintcastiq.dimcard')),
                ('parallel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mintcastiq.dimparallel')),
            ],
            options={
                'db_table': 'fact_team_master',
            },
        ),
        migrations.CreateModel(
            name='FactInventoryDetail',
            fields=[
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('acquired_at', models.DateTimeField()),
                ('source', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('identity_string', models.CharField(db_index=True, max_length=255)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('upc', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mintcastiq.dimgrade')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mintcastiq.factinventory')),
                ('player_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mintcastiq.factplayermaster')),
                ('team_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mintcastiq.factteammaster')),
            ],
            options={
                'db_table': 'fact_inventory_detail',
            },
        ),
        migrations.CreateModel(
            name='BridgePlayerTeam',
            fields=[
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('identity_string', models.TextField(editable=False)),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mintcastiq.factplayermaster')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mintcastiq.factteammaster')),
            ],
            options={
                'db_table': 'bridge_player_team',
            },
        ),
        migrations.CreateModel(
            name='DimCardParallel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('identity_string', models.TextField(editable=False)),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_parallels', to='mintcastiq.dimcard')),
                ('parallel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parallel_cards', to='mintcastiq.dimparallel')),
            ],
            options={
                'db_table': 'dim_card_parallel',
                'constraints': [models.UniqueConstraint(fields=('card', 'parallel'), name='uq_card_parallel_pair')],
            },
        ),
        migrations.CreateModel(
            name='DimParallelSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('identity_string', models.TextField(editable=False)),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('parallel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parallel_sets', to='mintcastiq.dimparallel')),
                ('card_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='set_parallels', to='mintcastiq.dimset')),
            ],
            options={
                'db_table': 'dim_parallel_set',
                'constraints': [models.UniqueConstraint(fields=('parallel', 'card_set'), name='uq_parallel_set_pair')],
            },
        ),
        migrations.AddConstraint(
            model_name='dimcard',
            constraint=models.UniqueConstraint(fields=('cardset', 'card_number'), name='unique_card_identity'),
        ),
        migrations.AddConstraint(
            model_name='factinventorydetail',
            constraint=models.UniqueConstraint(fields=('identity_string',), name='unique_inventory_detail'),
        ),
        migrations.AddConstraint(
            model_name='bridgeplayerteam',
            constraint=models.UniqueConstraint(fields=('player', 'team'), name='unique_player_team_bridge'),
        ),
    ]
