# Generated by Django 5.2.8 on 2025-12-17 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mintcastiq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bridgeplayerteam',
            name='identity_string',
        ),
        migrations.RemoveField(
            model_name='dimcard',
            name='identity_string',
        ),
        migrations.RemoveField(
            model_name='dimcardparallel',
            name='identity_string',
        ),
        migrations.RemoveField(
            model_name='dimgrade',
            name='identity_string',
        ),
        migrations.RemoveField(
            model_name='dimparallel',
            name='identity_string',
        ),
        migrations.RemoveField(
            model_name='dimparallelset',
            name='identity_string',
        ),
        migrations.RemoveField(
            model_name='dimsessions',
            name='identity_string',
        ),
        migrations.RemoveField(
            model_name='dimset',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='dimset',
            name='identity_string',
        ),
        migrations.RemoveField(
            model_name='dimusers',
            name='identity_string',
        ),
        migrations.RemoveField(
            model_name='factcardevents',
            name='identity_string',
        ),
        migrations.RemoveField(
            model_name='factinventory',
            name='identity_string',
        ),
        migrations.RemoveField(
            model_name='factplayermaster',
            name='identity_string',
        ),
        migrations.RemoveField(
            model_name='factteammaster',
            name='identity_string',
        ),
    ]
