# Generated by Django 5.2.8 on 2025-11-28 03:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mintcastiq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimCardParallel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_run', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='factmetrics',
            name='event',
        ),
        migrations.RenameField(
            model_name='dimset',
            old_name='ssubset_name',
            new_name='subset_name',
        ),
        migrations.RemoveField(
            model_name='dimcard',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='dimcard',
            name='format',
        ),
        migrations.RemoveField(
            model_name='dimgrade',
            name='grading_standard',
        ),
        migrations.RemoveField(
            model_name='dimgrade',
            name='overlay_ref',
        ),
        migrations.RemoveField(
            model_name='dimsessions',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dimusers',
            name='id',
        ),
        migrations.AddField(
            model_name='dimcard',
            name='card_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='dimcard',
            name='identity_string',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dimcard',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('i', 'inactive')], db_index=True, default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='dimcard',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dimcardhash',
            name='hash_run',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dimcardhash',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('i', 'inactive')], db_index=True, default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='dimgrade',
            name='grading_company',
            field=models.CharField(default='RAW', max_length=50),
        ),
        migrations.AddField(
            model_name='dimgrade',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('i', 'inactive')], db_index=True, default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='dimparallel',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('i', 'inactive')], db_index=True, default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='dimsessions',
            name='session_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='dimsessions',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('i', 'inactive')], db_index=True, default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='dimset',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('i', 'inactive')], db_index=True, default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='dimusers',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('i', 'inactive')], db_index=True, default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='dimusers',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='factcardevents',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('i', 'inactive')], db_index=True, default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='factchecklistitem',
            name='identity_string',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='factchecklistitem',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('i', 'inactive')], db_index=True, default='a', max_length=1),
        ),
        migrations.AddField(
            model_name='factinventory',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimcard'),
        ),
        migrations.AddField(
            model_name='factinventory',
            name='identity_string',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='factinventory',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('i', 'inactive')], db_index=True, default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='dimcard',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dimcard',
            name='parallel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mintcastiq.dimparallel'),
        ),
        migrations.AlterField(
            model_name='dimcard',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mintcastiq.dimset'),
        ),
        migrations.AlterField(
            model_name='dimcardhash',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mintcastiq.dimcard'),
        ),
        migrations.AlterField(
            model_name='dimcardhash',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dimcardhash',
            name='hash_position',
            field=models.CharField(choices=[('full_card', 'Full Card'), ('NE', 'Northeast'), ('N', 'North'), ('NW', 'Northwest'), ('W', 'West'), ('SW', 'Southwest'), ('S', 'South'), ('SE', 'Southeast'), ('E', 'East'), ('Center', 'Center')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='dimcardhash',
            name='hash_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dimcardhash',
            name='hash_value',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='dimgrade',
            name='grade_label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dimgrade',
            name='numeric_value',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dimparallel',
            name='parallel_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dimparallel',
            name='parallel_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dimparallel',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mintcastiq.dimset'),
        ),
        migrations.AlterField(
            model_name='dimsessions',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dimsessions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mintcastiq.dimusers'),
        ),
        migrations.AlterField(
            model_name='dimset',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dimset',
            name='set_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dimusers',
            name='invited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dimusers',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dimusers',
            name='is_contributor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dimusers',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dimusers',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='factcardevents',
            name='action_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='factcardevents',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mintcastiq.dimcard'),
        ),
        migrations.AlterField(
            model_name='factcardevents',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mintcastiq.dimgrade'),
        ),
        migrations.AlterField(
            model_name='factcardevents',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mintcastiq.dimset'),
        ),
        migrations.AlterField(
            model_name='factcardevents',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='factcardevents',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mintcastiq.dimusers'),
        ),
        migrations.AlterField(
            model_name='factchecklistitem',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mintcastiq.dimcard'),
        ),
        migrations.AlterField(
            model_name='factchecklistitem',
            name='parallel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mintcastiq.dimparallel'),
        ),
        migrations.AlterField(
            model_name='factchecklistitem',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mintcastiq.dimset'),
        ),
        migrations.AddConstraint(
            model_name='dimcard',
            constraint=models.UniqueConstraint(fields=('identity_string',), name='unique_card_identity'),
        ),
        migrations.AddConstraint(
            model_name='dimcardhash',
            constraint=models.UniqueConstraint(fields=('card', 'hash_run', 'hash_position'), name='unique_card_run_position'),
        ),
        migrations.AddConstraint(
            model_name='dimgrade',
            constraint=models.UniqueConstraint(fields=('grading_company', 'numeric_value'), name='unique_grade'),
        ),
        migrations.AddConstraint(
            model_name='dimparallel',
            constraint=models.UniqueConstraint(fields=('set', 'parallel_name'), name='unique_set_parallel'),
        ),
        migrations.AddConstraint(
            model_name='dimset',
            constraint=models.UniqueConstraint(fields=('set_name', 'subset_name', 'publisher', 'set_year'), name='unique_set_subset'),
        ),
        migrations.AddConstraint(
            model_name='factchecklistitem',
            constraint=models.UniqueConstraint(fields=('identity_string',), name='unique_checklist_identity'),
        ),
        migrations.AddConstraint(
            model_name='factinventory',
            constraint=models.UniqueConstraint(fields=('identity_string',), name='unique_inventory'),
        ),
        migrations.AddField(
            model_name='dimcardparallel',
            name='parallel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mintcastiq.dimparallel'),
        ),
        migrations.AddField(
            model_name='dimcardparallel',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mintcastiq.dimset'),
        ),
        migrations.DeleteModel(
            name='FactMetrics',
        ),
    ]
