# Generated by Django 5.2.8 on 2025-12-17 13:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mintcastiq', '0002_remove_bridgeplayerteam_identity_string_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactSessions',
            fields=[
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_token', models.CharField(max_length=255, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'fact_sessions',
            },
        ),
        migrations.CreateModel(
            name='FactUsersOTP',
            fields=[
                ('status', models.CharField(db_index=True, default='active', max_length=16)),
                ('otp_id', models.AutoField(primary_key=True, serialize=False)),
                ('otp_hash', models.CharField(max_length=128)),
                ('delivery_method', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_user_otp',
            },
        ),
        migrations.RemoveField(
            model_name='dimsessions',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='dimparallel',
            name='uq_parallel_id',
        ),
        migrations.RemoveConstraint(
            model_name='factinventorydetail',
            name='unique_inventory_detail',
        ),
        migrations.RenameField(
            model_name='dimparallel',
            old_name='parallel_id',
            new_name='parallel_name',
        ),
        migrations.RemoveField(
            model_name='dimusers',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='dimusers',
            name='invited',
        ),
        migrations.RemoveField(
            model_name='dimusers',
            name='otp_delivery',
        ),
        migrations.RemoveField(
            model_name='factcardevents',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='factinventory',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='factinventorydetail',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='factplayermaster',
            name='checksum',
        ),
        migrations.RemoveField(
            model_name='factteammaster',
            name='checksum',
        ),
        migrations.AlterField(
            model_name='dimcard',
            name='cardset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='mintcastiq.dimset'),
        ),
        migrations.AlterField(
            model_name='dimparallel',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='dimparallel',
            constraint=models.UniqueConstraint(fields=('parallel_name',), name='uq_parallel_name'),
        ),
        migrations.AddField(
            model_name='factsessions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mintcastiq.dimusers'),
        ),
        migrations.AddField(
            model_name='factusersotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mintcastiq.dimusers'),
        ),
        migrations.DeleteModel(
            name='DimSessions',
        ),
    ]
