# Generated by Django 5.2.8 on 2025-12-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mintcastiq', '0002_checklistupload'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dimparallel',
            name='unique_set_parallel',
        ),
        migrations.RenameField(
            model_name='dimcard',
            old_name='set',
            new_name='cardset',
        ),
        migrations.RenameField(
            model_name='dimparallel',
            old_name='set',
            new_name='cardset',
        ),
        migrations.AddField(
            model_name='dimset',
            name='print_run',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklistupload',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='dimparallel',
            constraint=models.UniqueConstraint(fields=('cardset', 'parallel_name'), name='unique_set_parallel'),
        ),
        migrations.AlterModelTable(
            name='checklistupload',
            table='checklist_upload',
        ),
    ]
