# Generated by Django 5.2.8 on 2025-11-28 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mintcastiq', '0002_dimcardparallel_remove_factmetrics_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimcardhash',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mintcastiq.dimcard'),
        ),
    ]
