# Generated by Django 5.2.8 on 2025-12-03 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mintcastiq', '0003_remove_dimparallel_unique_set_parallel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimcard',
            name='parallel',
        ),
        migrations.RemoveField(
            model_name='factinventorydetail',
            name='card',
        ),
        migrations.AddField(
            model_name='dimset',
            name='identity_string',
            field=models.CharField(default=models.CharField(max_length=128), max_length=64),
        ),
        migrations.AlterField(
            model_name='dimcard',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='dimcard',
            name='team_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='dimparallel',
            name='parallel_name',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='FactPlayerMaster',
            fields=[
                ('status', models.CharField(choices=[('a', 'active'), ('i', 'inactive')], db_index=True, default='a', max_length=1)),
                ('identity_string', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('hash_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=128)),
                ('player_name', models.CharField(max_length=64)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimcard')),
                ('parallel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimparallel')),
            ],
            options={
                'db_table': 'fact_player_master',
            },
        ),
        migrations.AddField(
            model_name='factinventorydetail',
            name='player_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.factplayermaster'),
        ),
        migrations.CreateModel(
            name='FactTeamMaster',
            fields=[
                ('status', models.CharField(choices=[('a', 'active'), ('i', 'inactive')], db_index=True, default='a', max_length=1)),
                ('identity_string', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('hash_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=128)),
                ('team_name', models.CharField(max_length=64)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimcard')),
                ('parallel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimparallel')),
            ],
            options={
                'db_table': 'fact_team_master',
            },
        ),
        migrations.AddField(
            model_name='factinventorydetail',
            name='team_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.factteammaster'),
        ),
        migrations.CreateModel(
            name='BridgePlayerTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player_master', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.factplayermaster')),
                ('team_master', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.factteammaster')),
            ],
            options={
                'db_table': 'bridge_player_team',
                'constraints': [models.UniqueConstraint(fields=('player_master', 'team_master'), name='unique_player_team_bridge')],
            },
        ),
    ]
