# Generated by Django 5.2.8 on 2025-12-18 14:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mintcastiq', '0003_factsessions_factusersotp_remove_dimsessions_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactChecklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=255)),
                ('source_sheet', models.CharField(blank=True, max_length=255, null=True)),
                ('source_row', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_parallel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_entries', to='mintcastiq.dimcardparallel')),
            ],
            options={
                'verbose_name': 'Checklist Entry',
                'verbose_name_plural': 'Checklist Entries',
                'db_table': 'fact_checklist_entry',
            },
        ),
        migrations.CreateModel(
            name='StagingChecklistRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_row', models.JSONField(help_text='Original contributor input, unmodified.')),
                ('normalized_set', models.CharField(blank=True, max_length=200, null=True)),
                ('normalized_card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('normalized_player', models.CharField(blank=True, max_length=200, null=True)),
                ('normalized_parallel', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATED', 'Validated'), ('ERROR', 'Error'), ('READY_FOR_LOAD', 'Ready for Load'), ('LOADED', 'Loaded')], db_index=True, default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_rows', to='mintcastiq.dimcard')),
                ('parallel_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_rows', to='mintcastiq.dimparallel')),
                ('set_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staging_rows', to='mintcastiq.dimset')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['status'], name='mintcastiq__status_fbb5de_idx')],
            },
        ),
    ]
