# Generated by Django 5.2.8 on 2025-11-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mintcastiq', '0003_alter_dimcardhash_card'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dimgrade',
            name='unique_grade',
        ),
        migrations.RemoveField(
            model_name='dimgrade',
            name='grading_company',
        ),
        migrations.AddField(
            model_name='dimgrade',
            name='grading_standard',
            field=models.CharField(db_index=True, default='RAW', max_length=50),
        ),
        migrations.AddField(
            model_name='dimgrade',
            name='overlay_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='dimgrade',
            constraint=models.UniqueConstraint(fields=('grading_standard', 'numeric_value', 'grade_label'), name='unique_grade'),
        ),
    ]
