# Generated by Django 5.2.8 on 2025-12-11 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mintcastiq', '0004_remove_dimcard_parallel_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dimparallel',
            name='unique_set_parallel',
        ),
        migrations.RemoveConstraint(
            model_name='dimset',
            name='unique_set_subset',
        ),
        migrations.RemoveField(
            model_name='dimparallel',
            name='cardset',
        ),
        migrations.RemoveField(
            model_name='dimset',
            name='identity_string',
        ),
        migrations.RemoveField(
            model_name='dimset',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='factplayermaster',
            name='identity_string',
        ),
        migrations.RemoveField(
            model_name='factteammaster',
            name='identity_string',
        ),
        migrations.AddField(
            model_name='dimparallel',
            name='card_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mintcastiq.dimset'),
        ),
        migrations.AddField(
            model_name='dimset',
            name='checksum',
            field=models.CharField(default=models.CharField(default='FIXME', max_length=128), max_length=64),
        ),
        migrations.AddField(
            model_name='dimset',
            name='friendly_name',
            field=models.CharField(default='FIXME', max_length=128),
        ),
        migrations.AddField(
            model_name='dimset',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dimcard',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='dimgrade',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='dimparallel',
            name='print_run',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dimparallel',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='dimsessions',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='dimset',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='dimusers',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='factcardevents',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='factinventory',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='factinventorydetail',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='factplayermaster',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='factteammaster',
            name='status',
            field=models.CharField(db_index=True, default='active', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='dimparallel',
            constraint=models.UniqueConstraint(fields=('parallel_name',), name='unique_parallel'),
        ),
        migrations.AddConstraint(
            model_name='dimset',
            constraint=models.UniqueConstraint(fields=('friendly_name',), name='unique_set'),
        ),
    ]
