# Generated by Django 5.2.8 on 2025-12-18 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mintcastiq', '0004_factchecklistentry_stagingchecklistrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagedSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(blank=True, max_length=128, null=True)),
                ('publisher', models.CharField(blank=True, max_length=64, null=True)),
                ('set_year', models.CharField(blank=True, max_length=32, null=True)),
                ('subset_name', models.CharField(blank=True, max_length=128, null=True)),
                ('brand', models.CharField(blank=True, max_length=64, null=True)),
                ('sport', models.CharField(blank=True, max_length=32, null=True)),
                ('set_code', models.CharField(blank=True, max_length=128, null=True)),
                ('source_file', models.CharField(blank=True, max_length=256, null=True)),
                ('ingest_session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Staged Set',
                'verbose_name_plural': 'Staged Sets',
            },
        ),
        migrations.CreateModel(
            name='StagedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_name', models.CharField(max_length=64, null=True)),
                ('raw_team_name', models.CharField(max_length=64, null=True)),
                ('raw_card_number', models.CharField(max_length=25, null=True)),
                ('raw_parallel_name', models.CharField(max_length=64, null=True)),
                ('raw_set_name', models.CharField(max_length=64, null=True)),
                ('ingest_batch_id', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cardset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mintcastiq.dimset')),
                ('parallel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mintcastiq.dimparallel')),
            ],
        ),
        migrations.CreateModel(
            name='StagedCardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_action_type', models.CharField(max_length=255, null=True)),
                ('raw_timestamp', models.DateTimeField(null=True)),
                ('raw_confidence_score', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('raw_processing_time_ms', models.IntegerField(null=True)),
                ('ingest_batch_id', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mintcastiq.dimcard')),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mintcastiq.dimgrade')),
                ('set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mintcastiq.dimset')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mintcastiq.dimusers')),
            ],
        ),
        migrations.CreateModel(
            name='StagedInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingest_batch_id', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mintcastiq.dimusers')),
            ],
        ),
        migrations.CreateModel(
            name='StagedInventoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_quantity', models.IntegerField(null=True)),
                ('raw_acquired_at', models.DateTimeField(null=True)),
                ('raw_source', models.TextField(null=True)),
                ('raw_notes', models.TextField(null=True)),
                ('raw_upc', models.CharField(max_length=255, null=True)),
                ('ingest_batch_id', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mintcastiq.dimgrade')),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mintcastiq.factinventory')),
                ('player_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mintcastiq.factplayermaster')),
                ('team_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mintcastiq.factteammaster')),
            ],
        ),
        migrations.CreateModel(
            name='StagedParallel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_parallel_name', models.CharField(max_length=64, null=True)),
                ('raw_print_run', models.PositiveBigIntegerField(null=True)),
                ('ingest_batch_id', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_set', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mintcastiq.dimset')),
            ],
        ),
        migrations.CreateModel(
            name='StagedPlayerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_full_name', models.CharField(max_length=128, null=True)),
                ('raw_player_name', models.CharField(max_length=64, null=True)),
                ('ingest_batch_id', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mintcastiq.dimcard')),
                ('parallel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mintcastiq.dimparallel')),
            ],
        ),
        migrations.CreateModel(
            name='StagedPlayerTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingest_batch_id', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mintcastiq.factplayermaster')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mintcastiq.factteammaster')),
            ],
        ),
        migrations.CreateModel(
            name='StagedTeamMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_full_name', models.CharField(max_length=128, null=True)),
                ('raw_team_name', models.CharField(max_length=64, null=True)),
                ('ingest_batch_id', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mintcastiq.dimcard')),
                ('parallel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mintcastiq.dimparallel')),
            ],
        ),
    ]
